# This workflow will build a Java project with Gradle

name: injector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifact
        run: ./gradlew publish --no-daemon
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_HASH: ${{ github.sha }}